name: ritme_examples_prep_data
channels:
  - https://packages.qiime2.org/qiime2/2024.5/amplicon/released/
  - https://packages.qiime2.org/qiime2/2024.5/metagenome/released/
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - black
  - flake8
  - geopandas
  - qiime2
  - q2cli
  - q2-alignment
  - q2-diversity
  - q2-feature-classifier
  - q2-feature-table
  - q2-fragment-insertion
  - q2-metadata
  - q2-phylogeny
  - q2-dada2
  - q2-demux
  - q2-fondue
  - q2-cutadapt
  - q2-quality-filter
  - q2-vsearch
  - rescript
  - isort
  - imageio
  - ipykernel
  - joypy
  - openpyxl
  - pre-commit
  - pip
  - ruff
  - seaborn
  - scipy
  - shapely>=1.8
  - xlrd>=2.0.1
  - pip:
    - lxml
